# Every time we push code, travis clones the git files, builds the image and runs the test suite

# We need super user permission
sudo: required
# Tell travis that we need docker
services: 
  - docker

before_install:
  - docker build -t maxblanck/docker-react -f Dockerfile.dev .

# series of command which have to be executed. "-- --coverage" to make sure test automatically exits
script:
  - docker run maxblanck/docker-react npm run test -- --coverage

# Create new Elastic beanstalk Service in AWS with plattform docker selected 
deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-159344145130"
  bucket_path: "docker-react"
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:  
    secure: "$AWS_SECRET_KEY"